// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhwzA-8Rukse5yqG-wI-0R-yOMUheH8C0',
    appId: '1:973904042413:web:bcba8b838b5cf911d4a924',
    messagingSenderId: '973904042413',
    projectId: 'semantics-learn',
    authDomain: 'semantics-learn.firebaseapp.com',
    storageBucket: 'semantics-learn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzd-jiXdbf_hAcRWSAaNZqYTFIXAsgaRA',
    appId: '1:973904042413:android:cd94fd5f070bfb91d4a924',
    messagingSenderId: '973904042413',
    projectId: 'semantics-learn',
    storageBucket: 'semantics-learn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1IzLCRxwNBKbnPk3qme3u0tcn3ONSacw',
    appId: '1:973904042413:ios:82dd70e5a7b834b1d4a924',
    messagingSenderId: '973904042413',
    projectId: 'semantics-learn',
    storageBucket: 'semantics-learn.appspot.com',
    iosClientId: '973904042413-2dcg9ncuv5e8g58obhja05cb6uk1l53u.apps.googleusercontent.com',
    iosBundleId: 'com.example.semantic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1IzLCRxwNBKbnPk3qme3u0tcn3ONSacw',
    appId: '1:973904042413:ios:82dd70e5a7b834b1d4a924',
    messagingSenderId: '973904042413',
    projectId: 'semantics-learn',
    storageBucket: 'semantics-learn.appspot.com',
    iosClientId: '973904042413-2dcg9ncuv5e8g58obhja05cb6uk1l53u.apps.googleusercontent.com',
    iosBundleId: 'com.example.semantic',
  );
}
