// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3cV-jRCDYIQp9yDphr0Kl0meqQF6Pjgo',
    appId: '1:263232090134:web:8fcd5d3f345df603c10537',
    messagingSenderId: '263232090134',
    projectId: 'semantic-stoic',
    authDomain: 'semantic-stoic.firebaseapp.com',
    databaseURL: 'https://semantic-stoic-default-rtdb.firebaseio.com',
    storageBucket: 'semantic-stoic.appspot.com',
    measurementId: 'G-ME6W3E2X76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADZ6vwKGJTvJ6M88qcb5oYvwtPMQd9hIg',
    appId: '1:263232090134:android:1d771b3feb76ff55c10537',
    messagingSenderId: '263232090134',
    projectId: 'semantic-stoic',
    databaseURL: 'https://semantic-stoic-default-rtdb.firebaseio.com',
    storageBucket: 'semantic-stoic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV3pWtQEWZW1bDKctPbvTOh_wYW0EsoE0',
    appId: '1:263232090134:ios:b6a2687df95549a7c10537',
    messagingSenderId: '263232090134',
    projectId: 'semantic-stoic',
    databaseURL: 'https://semantic-stoic-default-rtdb.firebaseio.com',
    storageBucket: 'semantic-stoic.appspot.com',
    iosClientId: '263232090134-l8unlvohnvfl2jsuirsdi367hp0jfskj.apps.googleusercontent.com',
    iosBundleId: 'com.example.semantic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV3pWtQEWZW1bDKctPbvTOh_wYW0EsoE0',
    appId: '1:263232090134:ios:b6a2687df95549a7c10537',
    messagingSenderId: '263232090134',
    projectId: 'semantic-stoic',
    databaseURL: 'https://semantic-stoic-default-rtdb.firebaseio.com',
    storageBucket: 'semantic-stoic.appspot.com',
    iosClientId: '263232090134-l8unlvohnvfl2jsuirsdi367hp0jfskj.apps.googleusercontent.com',
    iosBundleId: 'com.example.semantic',
  );
}
